# Generated by Django 6.0.1 on 2026-01-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('deposit_pending', 'Deposit (Pending)'), ('deposit_settled', 'Deposit (Settled)'), ('transfer', 'Transfer'), ('fee', 'Fee'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
