# Generated by Django 6.0.1 on 2026-01-27 18:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Benificiary',
            new_name='Beneficiary',
        ),
        migrations.RenameField(
            model_name='externalwirerequest',
            old_name='benificiary',
            new_name='beneficiary',
        ),
    ]
