# Generated by Django 6.0.1 on 2026-01-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_rename_benificiary_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalwirerequest',
            name='reference',
            field=models.CharField(default='', help_text='Internal transaction reference', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
